services:
  - type: static
    name: allot-system-frontend
    buildCommand: npm install --legacy-peer-deps --force && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://rwzzmixgxvazvxpvkygv.supabase.co
      - key: VITE_SUPABASE_KEY
        value: sb_publishable_pAf8uLK2cT-Vg9sEHgKJ_Q_EnPZVdqu